### ISSUE TITLE
Varnish example has EOL version 5

### ISSUE THREAD

**Issue by back-2-95** [lagoon-examples/drupal9-varnish#30]
Here https://github.com/lagoon-examples/drupal9-varnish/blob/main/docker-compose.yml#L102

https://endoflife.date/varnish

**Comment by tobybellwood** [comment]
We picked up some issues with varnish 6 on M1 Mac locally, but also never upgraded our examples. Varnish 7 looks more promising, and will be out soon!

**Comment by tobybellwood** [comment]
Now runs Varnish 7. Varnish 6 also works now the ARM fix has been backported
